### ISSUE TITLE
Why is SuperConsumer a private interface?

### ISSUE THREAD

**Issue by jlannoy** [Hervian/safety-mirror#5]
Hello.

Is there any particular reason the SuperConsumer interface is private? 
Use case : I want to offer kind of an API in one framework that handles "any possible lambda", and I need to get the corresponding method. I would have setup my method as having a SuperConsumer parameter... I know it kind of exposes your functional interface to the client, but the other option actually is to implement my own functional interfaces... Not so great.

Thank you,

Jonathan

**Comment by jlannoy** [comment]
I then exposed all consumer interfaces...

But to allow a common treatment, it's needed to have the SuperConsumer interface as public, and Types.createMethodFromSuperConsumer() too.

**Comment by Hervian** [comment]
Thanks for your comment jlannoy!
I am not maintaining this library since I ran into some problems as it turned out that the library only works for certain java distributions. See the updated README file.

**Comment by jlannoy** [comment]
I've read the thread on stackoverflow, but I probably miss the point. Your library targets the method references, not the anonymous methods. For me it was clear... In the framework I'm setting up, your library is used to offer a easy-to-read way of targeting class methods. If anyone tries to use an anonymous methods, it'll fail at runtime with an explicit error.

And in this scope it works perfectly ; I didn't saw something that could be distribution-dependent (again, I'm speaking only for methods references). I can propose a PR for my own request... Or if you are sure of not maintaining it anymore, I'll just copy-paste your sources in my code. Keeping package/licence/author of course :)

Thank you anyway.

**Comment by Hervian** [comment]
Hi again @jlannoy . I have resurfaced after some busy years with children and new work and have released a completely rewritten and expanded version of this project.
Are you still using it/interested in it?
If yes, I would love to get some feedback on the new version. It is in Maven Central. The README is a good starting point. 
Be aware that classes have been renamed and the package structure has changed.

**Comment by jlannoy** [comment]
Hello @Hervian. Not sure, but I think I'll not be interested anymore in a couple of days. I'm migrating my framework ([Weblith.io](https://weblith.io)) to [Quarkus](https://quarkus.io) which moves all my startup reflections things to somewhere during the compile time. I must still rewrite the part where I was using (a local copy of) your library. Thank you ;)

**Comment by jlannoy** [comment]
Hi @Hervian. Only yo tell I updated my previous project, removing your code I had copy pasted and using now the maven central release. Everything seems to work fine :) Thank you.
